const c=document.getElementById('game'),x=c.getContext('2d'),scoreEl=document.getElementById('score'),ls=document.getElementById('leftScore'),rs=document.getElementById('rightScore'),serveEl=document.getElementById('serveText'),overlay=document.getElementById('overlay'),title=document.getElementById('overlayTitle'),text=document.getElementById('overlayText'),start=document.getElementById('startBtn');
const W=900,H=560,GROUND=500,NETX=450,NETH=145,GRAV=.42;let keys={},running=false,last=0,leftScore=0,rightScore=0,ball,particles=[],serveState='player',servePressed=false,hitCooldown=0,cpuHitCooldown=0,shake=0;
const p1={x:220,y:GROUND-35,vx:0,vy:0,r:35,side:'l',jump:false,anim:0};const cpu={x:680,y:GROUND-35,vx:0,vy:0,r:35,side:'r',jump:false,anim:0};
function resetBall(server='player'){serveState=server;servePressed=false;hitCooldown=0;cpuHitCooldown=0;if(server==='player'){ball={x:p1.x+36,y:p1.y-7,vx:0,vy:0,r:17,spin:0,held:true,lastHit:'player'};serveEl.textContent='공을 들고 있음 · SPACE 서브'}else{ball={x:cpu.x-36,y:cpu.y-7,vx:0,vy:0,r:17,spin:0,held:true,lastHit:'cpu'};serveEl.textContent='CPU가 서브 준비';setTimeout(()=>{if(running&&serveState==='cpu')cpuServe()},700)}}
function cpuServe(){if(serveState!=='cpu'||!running)return;ball.held=false;ball.vx=-5.4;ball.vy=-9.5;ball.lastHit='cpu';serveState='rally';serveEl.textContent='PLAY';burst(ball.x,ball.y,8)}
function resetMatch(){leftScore=rightScore=0;updateScore();p1.x=220;cpu.x=680;resetBall('player');particles=[]}
function updateScore(){ls.textContent=leftScore;rs.textContent=rightScore;scoreEl.textContent=`${leftScore} : ${rightScore}`}
function startGame(){resetMatch();overlay.classList.add('hidden');running=true;serveState='player';servePressed=false;serveEl.textContent='공을 들고 있음 · SPACE 서브'}
function winPoint(side){if(side==='l')leftScore++;else rightScore++;updateScore();burst(ball.x,ball.y,18);shake=7;if(leftScore>=7||rightScore>=7){running=false;title.textContent=leftScore>rightScore?'YOU WIN!':'CPU WIN';text.innerHTML=`최종 스코어<br>${leftScore} : ${rightScore}`;start.textContent='다시 하기';overlay.classList.remove('hidden')}else{resetBall(side==='l'?'player':'cpu')}}
function movePlayer(p,dt){let dir=0;if(p===p1){if(keys.ArrowLeft||keys.a)dir--;if(keys.ArrowRight||keys.d)dir++}p.vx+=(dir*1.35-p.vx)*.24;p.x+=p.vx*dt;let min=p.side==='l'?55:NETX+38,max=p.side==='l'?NETX-38:W-55;p.x=Math.max(min,Math.min(max,p.x));if((keys.w||keys.ArrowUp)&&!p.jump){p.vy=-10.5;p.jump=true}p.vy+=GRAV*dt;p.y+=p.vy*dt;if(p.y>=GROUND-p.r){p.y=GROUND-p.r;p.vy=0;p.jump=false}}
function moveCPU(dt){let target=cpu.x;if(ball&&!ball.held&&ball.x>NETX&&ball.vx>0)target=ball.x;else if(ball&&!ball.held&&ball.x>NETX)target=ball.x+(ball.vx>0?25:-25);else target=700;let d=target-cpu.x;cpu.vx+=(Math.max(-1,Math.min(1,d/75))*1.25-cpu.vx)*.19;cpu.x+=cpu.vx*dt;cpu.x=Math.max(NETX+38,Math.min(W-55,cpu.x));if(ball&&!ball.held&&ball.x>NETX&&ball.y<390&&Math.abs(ball.x-cpu.x)<68&&!cpu.jump){cpu.vy=-10.2;cpu.jump=true}cpu.vy+=GRAV*dt;cpu.y+=cpu.vy*dt;if(cpu.y>=GROUND-cpu.r){cpu.y=GROUND-cpu.r;cpu.vy=0;cpu.jump=false}}
function doHit(p,strong=false){if(!ball||ball.held)return false;let dx=ball.x-p.x,dy=ball.y-p.y,d=Math.hypot(dx,dy);let reach=strong?78:68;if(d>ball.r+reach)return false;let dir=p.side==='l'?1:-1;let nx=d?dx/d:dir,ny=d?dy/d:-1;let topAttack=p.jump&&ball.y<p.y-2;let power=strong&&topAttack?10.5:strong?8.3:6.6;ball.x=p.x+nx*(ball.r+reach*.45);ball.y=p.y+ny*(ball.r+reach*.45);if(strong&&topAttack){ball.vx=dir*power*1.15+p.vx*.7;ball.vy=5.2;shake=5;burst(ball.x,ball.y,16)}else{ball.vx=dir*power+nx*1.2+p.vx*.7;ball.vy=Math.min(-5.2,ny*power-3.5);burst(ball.x,ball.y,7)}ball.lastHit=p===p1?'player':'cpu';return true}
function hitByPlayer(){if(hitCooldown>0||!ball||ball.held)return;if(keys.x||keys.X){if(doHit(p1,true))hitCooldown=20}else if(keys.z||keys.Z){if(doHit(p1,false))hitCooldown=18}}
function hitByCPU(){if(cpuHitCooldown>0||!ball||ball.held||ball.x<NETX)return;let dist=Math.hypot(ball.x-cpu.x,ball.y-cpu.y);let strong=cpu.jump&&ball.y<cpu.y-8&&dist<88;if(dist<74&&(ball.vx>0||ball.lastHit==='player')){if(doHit(cpu,strong))cpuHitCooldown=22}}
function update(dt){if(!running)return;hitCooldown=Math.max(0,hitCooldown-dt);cpuHitCooldown=Math.max(0,cpuHitCooldown-dt);if(serveState==='player'&&ball.held){ball.x=p1.x+36;ball.y=p1.y-7;if(keys[' ']&&!servePressed){servePressed=true;ball.held=false;serveState='rally';ball.vx=5.7;ball.vy=-9.6;ball.lastHit='player';serveEl.textContent='PLAY';burst(ball.x,ball.y,10)}}movePlayer(p1,dt);moveCPU(dt);if(!ball.held){ball.vy+=GRAV*dt;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.spin+=ball.vx*.04;ball.vx*=.997;if(ball.x-ball.r<8){ball.x=8+ball.r;ball.vx=Math.abs(ball.vx)}if(ball.x+ball.r>W-8){ball.x=W-8-ball.r;ball.vx=-Math.abs(ball.vx)}if(ball.y-ball.r<55){ball.y=55+ball.r;ball.vy=Math.abs(ball.vy)*.75}hitByPlayer();hitByCPU();if(ball.x>NETX-18&&ball.x<NETX+18&&ball.y>GROUND-NETH){if(ball.x<NETX){ball.x=NETX-18;ball.vx=-Math.abs(ball.vx)}else{ball.x=NETX+18;ball.vx=Math.abs(ball.vx)}}if(ball.y+ball.r>=GROUND){winPoint(ball.x<NETX?'r':'l')}}for(const q of particles){q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=.08*dt;q.life-=dt}particles=particles.filter(q=>q.life>0);shake*=.84}
function burst(px,py,n=10){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=1+Math.random()*4.5;particles.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s-2,life:20+Math.random()*24})}}
function draw(){x.save();if(shake>.5)x.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);x.clearRect(-20,-20,W+40,H+40);let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#8ddcff');g.addColorStop(1,'#e8f9ff');x.fillStyle=g;x.fillRect(0,0,W,H);x.fillStyle='#76c66d';x.fillRect(0,GROUND,W,H-GROUND);x.fillStyle='#5da95a';x.fillRect(0,GROUND,W,7);x.fillStyle='#fff';x.fillRect(NETX-6,GROUND-NETH,12,NETH);x.fillStyle='#d8e5eb';x.fillRect(NETX-10,GROUND-NETH-8,20,8);drawShadow(p1);drawShadow(cpu);drawMonster(p1);drawMonster(cpu);drawBall();for(const q of particles){x.globalAlpha=q.life/44;x.fillStyle='#ffe047';x.fillRect(q.x,q.y,5,5)}x.globalAlpha=1;x.restore()}
function drawShadow(p){x.save();x.globalAlpha=.18;x.fillStyle='#19384a';x.beginPath();x.ellipse(p.x,GROUND+4,38,8,0,0,Math.PI*2);x.fill();x.restore()}
function drawMonster(p){x.save();x.translate(p.x,p.y);let flip=p.side==='r'?-1:1;x.scale(flip,1);let bob=p.jump?0:-Math.abs(Math.sin(performance.now()*.008))*1.5;x.translate(0,bob);x.fillStyle='#f4c92f';x.beginPath();x.ellipse(0,5,29,36,0,0,Math.PI*2);x.fill();x.beginPath();x.moveTo(-20,-22);x.lineTo(-29,-58);x.lineTo(-8,-43);x.lineTo(5,-56);x.lineTo(12,-27);x.closePath();x.fill();x.fillStyle='#202a32';x.beginPath();x.arc(-10,-3,3.8,0,Math.PI*2);x.arc(10,-3,3.8,0,Math.PI*2);x.fill();x.fillStyle='#e9544f';x.beginPath();x.arc(-19,9,6,0,Math.PI*2);x.arc(19,9,6,0,Math.PI*2);x.fill();x.strokeStyle='#9b721b';x.lineWidth=3;x.beginPath();x.moveTo(-6,12);x.quadraticCurveTo(0,18,6,12);x.stroke();x.fillStyle='#f0a51e';x.beginPath();x.moveTo(-27,21);x.lineTo(-48,32);x.lineTo(-30,13);x.fill();x.beginPath();x.moveTo(27,21);x.lineTo(48,32);x.lineTo(30,13);x.fill();x.restore()}
function drawBall(){if(!ball)return;x.save();x.translate(ball.x,ball.y);x.rotate(ball.spin);x.fillStyle='#fff';x.beginPath();x.arc(0,0,ball.r,0,Math.PI*2);x.fill();x.strokeStyle='#40515d';x.lineWidth=2;x.stroke();x.strokeStyle='#9aaab4';x.beginPath();x.arc(0,0,11,-1.1,1.1);x.stroke();x.restore()}
window.addEventListener('keydown',e=>{keys[e.key]=true;if([' ','ArrowLeft','ArrowRight','ArrowUp','z','Z','x','X'].includes(e.key))e.preventDefault()});window.addEventListener('keyup',e=>{keys[e.key]=false;if(e.key===' ')servePressed=false});document.querySelectorAll('.mobile-controls button').forEach(b=>{let k=b.dataset.key;let map={left:'ArrowLeft',right:'ArrowRight',jump:'w',hit:'z',spike:'x'};const on=e=>{e.preventDefault();keys[map[k]]=true};const off=e=>{e.preventDefault();keys[map[k]]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});start.onclick=()=>startGame();document.getElementById('resetBtn').onclick=()=>{title.textContent='READY?';text.innerHTML='공을 들고 시작합니다.<br>SPACE로 서브 · Z 일반타격 · X 스파이크';start.textContent='게임 시작';resetMatch();overlay.classList.remove('hidden');running=false};resetMatch();function loop(t){let dt=Math.min(1.8,(t-last)/16.67||1);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);