const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score'),limitEl=document.getElementById('limit'),bestEl=document.getElementById('best'),speedEl=document.getElementById('speed'),plateEl=document.getElementById('plate'),statusEl=document.getElementById('status'),overlay=document.getElementById('overlay'),titleEl=document.getElementById('overlayTitle'),textEl=document.getElementById('overlayText'),startBtn=document.getElementById('startBtn'),flashBtn=document.getElementById('flashBtn'),resetBtn=document.getElementById('resetBtn');
const evidence=document.getElementById('evidence'),evidenceCanvas=document.getElementById('evidenceCanvas'),ectx=evidenceCanvas.getContext('2d'),evidenceTitle=document.getElementById('evidenceTitle'),evidenceTime=document.getElementById('evidenceTime'),evidenceVehicle=document.getElementById('evidenceVehicle'),evidencePlate=document.getElementById('evidencePlate'),evidenceSpeed=document.getElementById('evidenceSpeed'),evidenceLimit=document.getElementById('evidenceLimit'),evidenceTiming=document.getElementById('evidenceTiming'),evidenceNote=document.getElementById('evidenceNote'),photoStamp=document.getElementById('photoStamp'),continueBtn=document.getElementById('continueBtn');
const W=900,H=560,ROAD_Y=350,CAMERA_X=455;let running=false,score=0,best=0,round=0,last=0,vehicle=null,particles=[],flash=0,shake=0,shotLocked=false,keys={},pendingResult=null;
const limits=[50,60,70,80,90];
const vehicleTypes=[
{name:'MODEL 3',kind:'sedan',baseW:118,baseH:48,colors:['#dce5e8','#20272b','#53656d']},
{name:'SUV',kind:'suv',baseW:132,baseH:58,colors:['#c9d0d2','#20262a','#4e5d64']},
{name:'HATCHBACK',kind:'hatch',baseW:108,baseH:50,colors:['#b8c7ca','#20262b','#56666c']},
{name:'VAN',kind:'van',baseW:145,baseH:62,colors:['#e1e2dd','#22282b','#59676b']},
{name:'SPORTS',kind:'sports',baseW:112,baseH:43,colors:['#b82f31','#1d2225','#59666b']},
{name:'PICKUP',kind:'pickup',baseW:142,baseH:57,colors:['#68777d','#1d2428','#4e5c62']}];
function rand(a,b){return a+Math.random()*(b-a)}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function makePlate(){return `${Math.floor(10+Math.random()*90)}${String.fromCharCode(65+Math.floor(Math.random()*26))}${Math.floor(1000+Math.random()*9000)}`}
function startGame(){score=0;round=0;scoreEl.textContent='0';overlay.classList.add('hidden');evidence.classList.remove('show');running=true;spawnVehicle()}
function spawnVehicle(){round++;shotLocked=false;const limit=limits[Math.min(limits.length-1,Math.floor((round-1)/3))];limitEl.textContent=limit;const fast=Math.random()<.72;const kmh=fast?Math.round(rand(limit+8,limit+105)):Math.round(rand(38,limit+4));const type=pick(vehicleTypes);const scale=rand(.72,1.34);const laneY=rand(ROAD_Y-88,ROAD_Y-8);const depth=(laneY-(ROAD_Y-88))/80;const w=type.baseW*scale*(.84+depth*.28),h=type.baseH*scale*(.84+depth*.28);vehicle={x:-w-40,y:laneY-h*.72,w,h,speed:kmh,limit,plate:makePlate(),target:fast,type,depth};speedEl.textContent=kmh;plateEl.textContent='---';statusEl.textContent='WAITING'}
function shoot(){if(!running||!vehicle||shotLocked)return;shotLocked=true;flash=10;shake=8;burst(CAMERA_X,ROAD_Y-70,20);const center=vehicle.x+vehicle.w*.5;const detectionY=vehicle.y+vehicle.h*.55;const distance=Math.hypot(center-CAMERA_X,(detectionY-(ROAD_Y-35))*.55);const timing=Math.max(0,1-distance/115);const legal=vehicle.speed<=vehicle.limit;let points=0,result='MISS';if(!legal&&timing>.72){const severity=vehicle.speed-vehicle.limit;points=Math.round(180+severity*12+timing*260);result='PERFECT CAPTURE'}else if(!legal&&timing>.35){const severity=vehicle.speed-vehicle.limit;points=Math.round(60+severity*7+timing*120);result='CAPTURED'}else if(legal){result='NO VIOLATION'}score+=points;best=Math.max(best,score);scoreEl.textContent=score;bestEl.textContent=best;plateEl.textContent=vehicle.plate;speedEl.textContent=vehicle.speed;statusEl.textContent=points?`${result} +${points}`:result;pendingResult={timing,legal,points,result,vehicle:{...vehicle}};drawEvidence(pendingResult);fillEvidenceText(pendingResult);setTimeout(()=>{if(running)showEvidence()},180)}
function showEvidence(){running=false;evidence.classList.add('show')}
function continueGame(){if(!pendingResult)return;evidence.classList.remove('show');running=true;spawnVehicle()}
function update(dt){if(!running)return;if(vehicle&&!shotLocked){vehicle.x+=vehicle.speed*.17*dt;speedEl.textContent=vehicle.speed;if(vehicle.x>W+100){shotLocked=true;statusEl.textContent=vehicle.target?'ESCAPED':'CLEAR';setTimeout(()=>{if(running)spawnVehicle()},500)}}for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=.09*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);flash=Math.max(0,flash-dt);shake*=.86}
function draw(){ctx.save();if(shake>.3)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.clearRect(-20,-20,W+40,H+40);drawSky();drawRoad();drawStreet();if(vehicle)drawCar(vehicle);drawCamera();drawAim();if(flash>0){ctx.fillStyle=`rgba(255,255,255,${Math.min(.9,flash/10)})`;ctx.fillRect(0,0,W,H)}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life/30);ctx.fillStyle='#fff';ctx.fillRect(p.x,p.y,p.s,p.s)}ctx.globalAlpha=1;ctx.restore()}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,ROAD_Y);g.addColorStop(0,'#8199a6');g.addColorStop(1,'#d9e0e1');ctx.fillStyle=g;ctx.fillRect(0,0,W,ROAD_Y);ctx.fillStyle='#aab5b8';ctx.fillRect(0,235,W,65);for(let i=0;i<9;i++){ctx.fillStyle=i%2?'#7f8b8e':'#6f7b7f';ctx.fillRect(i*120+20,245-(i%3)*12,75,55)}ctx.fillStyle='#d7d9d4';ctx.beginPath();ctx.arc(110,115,48,0,Math.PI*2);ctx.fill();ctx.fillStyle='#eef0ea';ctx.beginPath();ctx.arc(790,90,60,0,Math.PI*2);ctx.fill()}
function drawRoad(){ctx.fillStyle='#30363a';ctx.fillRect(0,ROAD_Y,W,H-ROAD_Y);ctx.fillStyle='#666d70';ctx.fillRect(0,ROAD_Y,W,5);ctx.fillStyle='#e8e3c9';for(let i=-1;i<12;i++)ctx.fillRect(i*105+(vehicle?(-vehicle.x*.45%105):0),ROAD_Y+78,62,5);ctx.fillStyle='#f4f1dd';ctx.fillRect(0,H-32,W,5)}
function drawStreet(){ctx.fillStyle='#4e575b';ctx.fillRect(65,185,8,165);ctx.fillStyle='#31383c';ctx.fillRect(53,176,32,12);ctx.fillStyle='#c7d0d2';ctx.beginPath();ctx.arc(69,171,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#7d878b';ctx.fillRect(810,205,7,145);ctx.fillStyle='#e5e8e8';ctx.fillRect(797,196,34,12)}
function drawCamera(){ctx.fillStyle='#4b565b';ctx.fillRect(CAMERA_X-5,ROAD_Y-112,10,112);ctx.fillStyle='#151d21';ctx.fillRect(CAMERA_X-23,ROAD_Y-135,46,30);ctx.fillStyle='#56646a';ctx.fillRect(CAMERA_X-18,ROAD_Y-130,36,20);ctx.fillStyle='#e1e9ea';ctx.beginPath();ctx.arc(CAMERA_X,ROAD_Y-120,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#b8c1c4';ctx.fillRect(CAMERA_X-32,ROAD_Y-8,64,8)}
function drawAim(){ctx.save();ctx.strokeStyle=flash?'#fff':'#dbe7ea88';ctx.lineWidth=2;ctx.setLineDash([6,7]);ctx.beginPath();ctx.moveTo(CAMERA_X,ROAD_Y-135);ctx.lineTo(CAMERA_X,ROAD_Y);ctx.stroke();ctx.setLineDash([]);ctx.strokeStyle='#ffffffaa';ctx.strokeRect(CAMERA_X-55,ROAD_Y-75,110,82);ctx.restore()}
function drawCar(v){ctx.save();ctx.translate(v.x,v.y);const s=v.w/v.type.baseW;ctx.scale(s,s);const w=v.type.baseW,h=v.type.baseH,body=v.type.colors[0],dark=v.type.colors[1],glass=v.type.colors[2];ctx.fillStyle=dark;ctx.beginPath();if(v.type.kind==='suv')ctx.roundRect(1,18,w-2,h-15,10);else if(v.type.kind==='van')ctx.roundRect(1,12,w-2,h-8,8);else if(v.type.kind==='pickup')ctx.roundRect(2,18,w-4,h-14,8);else ctx.roundRect(2,17,w-4,h-16,12);ctx.fill();ctx.fillStyle=body;ctx.beginPath();if(v.type.kind==='suv'){ctx.moveTo(18,20);ctx.lineTo(34,2);ctx.lineTo(91,2);ctx.lineTo(113,20)}else if(v.type.kind==='van'){ctx.moveTo(17,13);ctx.lineTo(27,0);ctx.lineTo(104,0);ctx.lineTo(126,13)}else if(v.type.kind==='pickup'){ctx.moveTo(20,19);ctx.lineTo(42,5);ctx.lineTo(80,5);ctx.lineTo(93,19);ctx.lineTo(126,19)}else if(v.type.kind==='sports'){ctx.moveTo(20,18);ctx.lineTo(42,5);ctx.quadraticCurveTo(60,-1,78,5);ctx.lineTo(98,18)}else{ctx.moveTo(25,17);ctx.lineTo(39,2);ctx.quadraticCurveTo(53,-6,70,2);ctx.lineTo(91,17)}ctx.closePath();ctx.fill();ctx.fillStyle=glass;ctx.beginPath();ctx.moveTo(v.type.kind==='van'?30:42,4);ctx.lineTo(v.type.kind==='van'?43:57,-2);ctx.lineTo(v.type.kind==='van'?78:68,2);ctx.lineTo(v.type.kind==='van'?98:76,15);ctx.lineTo(v.type.kind==='van'?28:39,15);ctx.closePath();ctx.fill();if(v.type.kind==='pickup'){ctx.fillStyle='#333d42';ctx.fillRect(91,7,29,13)}ctx.fillStyle='#f0f3f4';ctx.fillRect(w-30,22,18,9);ctx.fillStyle='#a52d2d';ctx.fillRect(2,22,8,7);ctx.fillStyle='#20282c';ctx.beginPath();ctx.arc(27,h-1,10,0,Math.PI*2);ctx.arc(w-28,h-1,10,0,Math.PI*2);ctx.fill();ctx.fillStyle='#aeb9bd';ctx.beginPath();ctx.arc(27,h-1,5,0,Math.PI*2);ctx.arc(w-28,h-1,5,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(w-49,30,31,9);ctx.fillStyle='#151a1d';ctx.font='bold 7px system-ui';ctx.textAlign='center';ctx.fillText(v.plate,w-33,37);drawDriver(ctx,w*.49,9,.78);ctx.restore()}
function drawDriver(c,x,y,s=1){c.save();c.translate(x,y);c.fillStyle='#1c252a';c.beginPath();c.arc(0,0,8*s,0,Math.PI*2);c.fill();c.fillStyle='#c99272';c.beginPath();c.arc(0,-1*s,4.7*s,0,Math.PI*2);c.fill();c.fillStyle='#20272b';c.beginPath();c.arc(-1,-3*s,5*s,Math.PI,Math.PI*2);c.fill();c.fillStyle='#fff';c.fillRect(-2.5*s,-1*s,1.4*s,1*s);c.fillRect(1.1*s,-1*s,1.4*s,1*s);c.fillStyle='#26343a';c.fillRect(-4*s,6*s,8*s,7*s);c.restore()}
function drawEvidence(r){const v=r.vehicle,t=r.timing,w=720,h=410;ectx.clearRect(0,0,w,h);const g=ectx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#758b96');g.addColorStop(.52,'#cbd2d1');g.addColorStop(.53,'#3b4245');g.addColorStop(1,'#242a2d');ectx.fillStyle=g;ectx.fillRect(0,0,w,h);ectx.fillStyle='#6b767a';ectx.fillRect(0,210,w,8);for(let i=0;i<8;i++){ectx.fillStyle=i%2?'#7b8588':'#626d70';ectx.fillRect(i*100+20,150-(i%3)*9,70,58)}const blur=Math.round(Math.max(0,1-t)*8);const carX=205,carY=190,carW=310,carH=128;if(blur>0){ectx.save();ectx.globalAlpha=.18;for(let i=-blur;i<=blur;i+=2)drawEvidenceCar(carX+i*3,carY,carW,carH,v,0);ectx.restore()}drawEvidenceCar(carX,carY,carW,carH,v,blur);ectx.fillStyle='#ffffffd9';ectx.fillRect(18,18,205,72);ectx.fillStyle='#17232e';ectx.font='900 11px ui-monospace,monospace';ectx.fillText('CAM-01  /  EVIDENCE',30,38);ectx.font='900 34px ui-monospace,monospace';ectx.fillText(`${v.speed} KM/H`,30,74);ectx.fillStyle='#fff';ectx.font='900 12px ui-monospace,monospace';ectx.fillText(new Date().toLocaleTimeString('ko-KR',{hour12:false}),575,30);ectx.fillText('FRAME '+String(round).padStart(4,'0'),575,48);ectx.strokeStyle=t>.72?'#b7ffb7':'#fff8';ectx.lineWidth=2;ectx.strokeRect(carX-20,carY-28,carW+40,carH+55)}
function drawEvidenceCar(x,y,w,h,v,blur){ectx.save();ectx.translate(x,y);const type=v.type,sx=w/type.baseW,sy=h/type.baseH;ectx.scale(sx,sy);const body=type.colors[0],dark=type.colors[1],glass=type.colors[2],bw=type.baseW,bh=type.baseH;ectx.fillStyle=dark;ectx.beginPath();ectx.roundRect(0,18,bw-4,bh-4,9);ectx.fill();ectx.fillStyle=body;ectx.beginPath();if(type.kind==='suv'){ectx.moveTo(18,19);ectx.lineTo(32,1);ectx.lineTo(94,1);ectx.lineTo(116,19)}else if(type.kind==='van'){ectx.moveTo(16,14);ectx.lineTo(27,0);ectx.lineTo(106,0);ectx.lineTo(128,14)}else if(type.kind==='pickup'){ectx.moveTo(20,19);ectx.lineTo(42,5);ectx.lineTo(82,5);ectx.lineTo(96,19);ectx.lineTo(128,19)}else if(type.kind==='sports'){ectx.moveTo(20,18);ectx.lineTo(42,5);ectx.quadraticCurveTo(60,-1,80,5);ectx.lineTo(99,18)}else{ectx.moveTo(24,18);ectx.lineTo(43,2);ectx.quadraticCurveTo(60,-7,78,2);ectx.lineTo(98,18)}ectx.closePath();ectx.fill();ectx.fillStyle=glass;ectx.beginPath();ectx.moveTo(type.kind==='van'?29:43,4);ectx.lineTo(type.kind==='van'?45:58,-3);ectx.lineTo(type.kind==='van'?80:69,2);ectx.lineTo(type.kind==='van'?100:78,16);ectx.lineTo(type.kind==='van'?27:40,16);ectx.closePath();ectx.fill();const faceBlur=Math.min(10,blur*1.5);if(faceBlur){ectx.save();ectx.filter=`blur(${faceBlur}px)`}drawDriver(ectx,bw*.51,12,2.3);if(faceBlur)ectx.restore();const plateX=bw*.66,plateY=40;if(blur>0){ectx.save();ectx.filter=`blur(${Math.max(2,blur*1.8)}px)`;ectx.fillStyle='#f4f4ef';ectx.fillRect(plateX-40,plateY,82,28);ectx.fillStyle='#161b1e';ectx.font='900 17px ui-monospace,monospace';ectx.textAlign='center';ectx.fillText(v.plate,plateX,plateY+20);ectx.restore();if(blur>=5){ectx.fillStyle='#e8ebe8';ectx.fillRect(plateX-40,plateY,82,28);ectx.fillStyle='#778084';ectx.fillRect(plateX-35,plateY+8,70,5)}}else{ectx.fillStyle='#f4f4ef';ectx.fillRect(plateX-40,plateY,82,28);ectx.fillStyle='#161b1e';ectx.font='900 17px ui-monospace,monospace';ectx.textAlign='center';ectx.fillText(v.plate,plateX,plateY+20)}ectx.fillStyle='#f5f7f8';ectx.fillRect(bw-66,28,42,22);ectx.fillStyle='#b33131';ectx.fillRect(14,28,17,16);ectx.fillStyle='#20282c';ectx.beginPath();ectx.arc(31,bh-2,13,0,Math.PI*2);ectx.arc(bw-35,bh-2,13,0,Math.PI*2);ectx.fill();ectx.fillStyle='#aeb9bd';ectx.beginPath();ectx.arc(31,bh-2,6,0,Math.PI*2);ectx.arc(bw-35,bh-2,6,0,Math.PI*2);ectx.fill();ectx.restore()}
function burst(px,py,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=rand(1,6);particles.push({x:px,y:py,vx:Math.cos(a)*s,vy:Math.sin(a)*s-2,life:rand(14,32),s:rand(2,5)})}}
function fillEvidenceText(r){const v=r.vehicle,t=r.timing,quality=t>.85?'EXCELLENT':t>.72?'GOOD':t>.35?'POOR':'UNREADABLE';evidenceTitle.textContent=r.points?`${r.result}  +${r.points}`:r.result;evidenceTime.textContent=`CAM-01 / FRAME ${String(round).padStart(4,'0')}`;evidenceVehicle.textContent=v.type.name;evidencePlate.textContent=t>.72?v.plate:t>.35?'BLURRED':'UNREADABLE';evidenceSpeed.textContent=v.speed;evidenceLimit.textContent=v.limit;evidenceTiming.textContent=quality;evidenceNote.textContent=r.legal?'정상 속도 차량 — 단속 대상 아님':t>.72?'단속선 통과 순간을 정확하게 포착했습니다.':'촬영 타이밍이 어긋나 차량·얼굴·번호판이 흐릿하게 기록되었습니다.';photoStamp.textContent=t>.72?'PHOTO EVIDENCE':t>.35?'PARTIAL EVIDENCE':'UNREADABLE EVIDENCE'}
function loop(t){const dt=Math.min(1.8,(t-last)/16.67||1);last=t;update(dt);draw();requestAnimationFrame(loop)}
window.addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();if(!keys.space){keys.space=true;shoot()}}});window.addEventListener('keyup',e=>{if(e.key===' ')keys.space=false});flashBtn.addEventListener('click',shoot);startBtn.addEventListener('click',startGame);continueBtn.addEventListener('click',continueGame);resetBtn.addEventListener('click',()=>{running=false;evidence.classList.remove('show');overlay.classList.remove('hidden');titleEl.textContent='READY?';textEl.innerHTML='차량의 속도를 확인하고 과속 차량을 단속하세요.<br>SPACE 또는 CAMERA로 촬영';startBtn.textContent='단속 시작';score=0;scoreEl.textContent='0';statusEl.textContent='CAMERA READY';vehicle=null;plateEl.textContent='---';speedEl.textContent='0';pendingResult=null});bestEl.textContent=best;requestAnimationFrame(loop);